spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/calculator
    username: postgres
    password: password
logging:
  level:
    org.springframework.data.r2dbc: Debug
---
spring:
  profiles: test
  r2dbc:
    url: r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    name: sa
    password:
---
spring:
  profiles: prod
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/calculator
    username: postgres
    password: password
  logging:
    level:
      org.springframework.data.r2dbc: Debug

