DROP TABLE IF EXISTS account_details ;
CREATE TABLE account_details ( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, account_id integer NOT NULL, bsb integer, opening_date date NOT NULL);
DROP TABLE IF EXISTS account_balance ;
CREATE TABLE account_balance ( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,account_id integer, amount decimal, bsb integer);
DROP TABLE IF EXISTS account_history ;
CREATE TABLE account_history ( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,account_id integer, amount decimal, bsb integer,
credited_date date, trn_type VARCHAR(100), credit_debit_indicator CHAR(1));
